# Generated by Django 4.0.5 on 2022-09-16 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0003_alter_document_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 16, 17, 39, 38, 934940)),
        ),
    ]
